export const SAVE_PASSWORD = 'SAVE_PASSWORD';
export const SAVE_PASSWORD_SUCCESS = 'SAVE_PASSWORD_SUCCESS';
export const SAVE_PASSWORD_FAILED = 'SAVE_PASSWORD_FAILED';
export const FETCH_PASSWORDS_SUCCESS = 'FETCH_PASSWORDS_SUCCESS';
export const FETCH_PASSWORDS_FAILED = 'FETCH_PASSWORDS_FAILED';